
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN" # VGG-16
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RELATION_ON: True
  ATTRIBUTE_ON: False
  FLIP_AUG: False            # if there is any left-right relation, FLIP AUG should be false
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.23232838, 0.63365731, 1.28478321, 3.15089189)   # from neural-motifs
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_PER_BATCH: False
    RPN_MID_CHANNEL: 256
  ROI_HEADS:
    USE_FPN: True
    POSITIVE_FRACTION: 0.5
    BG_IOU_THRESHOLD: 0.3
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 80
    NMS_FILTER_DUPLICATES: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES:    49    # #         151    # 151 for VG, 1201 for GQA
    MLP_HEAD_DIM: 4096
  ROI_ATTRIBUTE_HEAD:
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    USE_BINARY_LOSS: True           # choose binary, because cross_entropy loss deteriorate the box head, even with 0.1 weight
    POS_WEIGHT: 50.0
    ATTRIBUTE_LOSS_WEIGHT: 1.0
    NUM_ATTRIBUTES: 201             # 201 for VG, 501 for GQA
    MAX_ATTRIBUTES: 10             
    ATTRIBUTE_BGFG_SAMPLE: True    
    ATTRIBUTE_BGFG_RATIO: 3        
  ROI_RELATION_HEAD:
    GPSNET_MODULE:
      GRAPH_HIDDEN_DIM: 512
      GRAPH_ITERATION_NUM: 2
      ITERATE_MP_PAIR_REFINE: 2
      MP_ON_VALID_PAIRS: false
      MP_VALID_PAIRS_NUM: 200
      RELNESS_MP_WEIGHTING: false
    HETSGG:
      IS_EXPERT: true
      USE_REL_PN: false
      NUM_RELATION: 4
      N_BASES: 2
      H_DIM: 128
      FEATURE_UPDATE_STEP: 2
      SCORE_UPDATE_STEP: 2
      CLASS_AGG: 'mean'
      VANILLA: false
    FREQUENCY_BAIS: true  ## BGNN HETSGG
    CLASSIFIER: linear  #  BGNN HETSGG
    CLASSIFIER_WEIGHT_SCALE: false
    FIX_CLASSIFIER_WEIGHT: false
    FIX_FEATURE: false
    EDGE_FEATURES_REPRESENTATION: fusion # BGNN
    REL_OBJ_MULTI_TASK_LOSS: false # BGNN  Hetsgg
    USE_GT_BOX: True
    USE_GT_OBJECT_LABEL: True
    REQUIRE_BOX_OVERLAP: False              # for sgdet, during training, only train pairs with overlap
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: True    # for sgdet only, in case some gt boxes are missing
    NUM_CLASSES: 59     # #       51    # 51 for VG, 201 for GQA (not contain "to the left of" & "to the right of")
    BATCH_SIZE_PER_IMAGE: 4096 #1024      # sample as much as possible  CHANGE rs  2048 for HBB
    POSITIVE_FRACTION: 0.25
    CONTEXT_POOLING_DIM: 4096
    BGNN_CONTEXT_POOLING_DIM: 2048
    CONTEXT_HIDDEN_DIM: 512         #1024 for VCTree
    POOLING_ALL_LEVELS: True
    LABEL_SMOOTHING_LOSS: False
    FEATURE_EXTRACTOR: "RelationFeatureExtractor"
    #################### Select Relationship Model ####################
    #PREDICTOR: "MotifPredictor"
    #PREDICTOR: "VCTreePredictor"
    PREDICTOR: "TransformerPredictor"
#    PREDICTOR: "CausalAnalysisPredictor"
    ################# Parameters for Motif Predictor ##################
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_REL_LAYER: 1
    ############# Parameters for Causal Unbias Predictor ##############
    ### Implementation for paper "Unbiased Scene Graph Generation from Biased Training"
    CAUSAL:
      EFFECT_TYPE: 'none'             # candicates: 'TDE', 'NIE', 'TE', 'none'
      FUSION_TYPE: 'sum'              # candicates: 'sum', 'gate'         
      SEPARATE_SPATIAL: False         # separate spatial in union feature
      CONTEXT_LAYER: "motifs"         # candicates: motifs, vctree, vtranse
      SPATIAL_FOR_VISION: True
      EFFECT_ANALYSIS: True
    ############### Parameters for Transformer Predictor ##############
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      OBJ_LAYER: 4
      REL_LAYER: 2
      NUM_HEAD: 8
      KEY_DIM: 64
      VAL_DIM: 64
      INNER_DIM: 2048
    BGNN_MODULE:
      EDGE_FEATURES_REPRESENTATION: union
      GATING_WITH_RELNESS_LOGITS: false
      GRAPH_HIDDEN_DIM: 512
      GRAPH_ITERATION_NUM: 3
      APPLY_GT: False
      ITERATE_MP_PAIR_REFINE: 3
      RELATION_CONFIDENCE_AWARE: True
      MP_ON_VALID_PAIRS: True
      MP_VALID_PAIRS_NUM: 128
      RELNESS_MP_WEIGHTING: true
      RELNESS_MP_WEIGHTING_SCORE_RECALIBRATION_METHOD: learnable_scaling
      LEARNABLE_SCALING_WEIGHT: (3.12, 0.06)
      SHARE_PARAMETERS_EACH_ITER: false
      SHARE_RELATED_MODEL_ACROSS_REFINE_ITER: false
      SKIP_CONNECTION_ON_OUTPUT: false
      SPLIT_GRAPH4OBJ_REL: false
    OBJECT_CLASSIFICATION_MANNER: replace # BGNN HetSGG
    # RELATION_PROPOSAL_MODEL:  # BGNN
    #   FOCAL_LOSS_ALPHA: 0.2
    #   FOCAL_LOSS_GAMMA: 2.0
    #   EVAL_MODEL_AUC: false
    #   FIX_MODEL_AT_ITER: 3000
    #   IGNORE_FOREGROUND_BOXES_PAIRS: false
    #   METHOD: RelAwareRelFeature
    #   PAIR_NUMS_AFTER_FILTERING: 128
    #   PRETRAIN_ITER_RELNESS_MODULE: 2000
    #   PRETRAIN_RELNESS_MODULE: true
    #   PRE_CLSER_LOSS: focal_fgbg_norm
    #   REL_AWARE_PREDICTOR_TYPE: hybrid 
    #   SET_ON: true
    #   USE_RELATEDNESS_FOR_PREDICTION_RANKING: false
    #   USE_SAME_LABEL_WITH_CLSER: false
    #   VISUAL_FEATURES_ON: True
    # WORD_EMBEDDING_FEATURES: true
    RELATION_PROPOSAL_MODEL:  ## HestGG
      FOCAL_LOSS_ALPHA: 0.2
      FOCAL_LOSS_GAMMA: 2.0
      EVAL_MODEL_AUC: false
      FIX_MODEL_AT_ITER: 3000
      IGNORE_FOREGROUND_BOXES_PAIRS: false
      METHOD: "rel_pn"
      PAIR_NUMS_AFTER_FILTERING: 128
      PRETRAIN_ITER_RELNESS_MODULE: 2000
      PRETRAIN_RELNESS_MODULE: false 
      PRE_CLSER_LOSS: focal_fgbg_norm
      REL_AWARE_PREDICTOR_TYPE: hybrid 
      SET_ON: False
      USE_RELATEDNESS_FOR_PREDICTION_RANKING: false
      USE_SAME_LABEL_WITH_CLSER: false
      VISUAL_FEATURES_ON: True
    WORD_EMBEDDING_FEATURES: true
DATASETS:

  ### RS
  STAR_TRAIN: ("STAR_with_attribute_train",)
  STAR_VAL: ("STAR_with_attribute_val",)
  STAR_TEST: ("STAR_with_attribute_test",)

  AUG_TRAIN: ("AUG_with_attribute_train",)
  AUG_VAL: ("AUG_with_attribute_val",)
  AUG_TEST: ("AUG_with_attribute_test",)

  VG_TRAIN: ("VG_with_attribute_train",)
  VG_VAL: ("VG_with_attribute_val",)
  VG_TEST: ("VG_with_attribute_test",)

DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BIAS_LR_FACTOR: 1
  BASE_LR: 0.001
  # change when batch size change
  IMS_PER_BATCH: 1
  MAX_ITER: 16000
  WARMUP_ITERS: 500
  STEPS: (10000, 16000)
  # end change
  WARMUP_FACTOR: 0.1
  WARMUP_METHOD: linear
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 5.0
  VAL_PERIOD: 2000
  CHECKPOINT_PERIOD: 2000
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    # the following paramters are only used for WarmupReduceLROnPlateau
    TYPE: "WarmupReduceLROnPlateau"    # WarmupMultiStepLR, WarmupReduceLROnPlateau
    PATIENCE: 6
    THRESHOLD: 0.001
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3

OUTPUT_DIR: './output/relation_baseline'
TEST:
  IMS_PER_BATCH: 1
  ALLOW_LOAD_FROM_CACHE: False
  RELATION:
    SYNC_GATHER: True      # turn on will slow down the evaluation to solve the sgdet test out of memory problem
    REQUIRE_OVERLAP: False
    LATER_NMS_PREDICTION_THRES: 0.5
  CUSTUM_EVAL: False       # eval SGDet model on custum images, output a json
  CUSTUM_PATH: '.'         # the folder that contains the custum images, only jpg files are allowed  


Type : "Large_RS_OBB"

BASIC_ENCODER : 'Hybrid-Attention'

use_SBP: False
use_BAL: False